{
 "title": "ACM Leaf Hubs Overview All",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  { "title": "Cluster Lifecycle", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Pod Error Count",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum_over_time(sum by (cluster) (kube_pod_status_phase{namespace=~\"open-cluster-management|open-cluster-management-hub\",pod=~\"cluster-manager-.*|managedcluster-import-controller-.*|\",phase!~\"Running|Succeeded\"})[24h:24h])"
    },
    {
     "expr": "sum_over_time(sum by (cluster) (kube_pod_status_phase{namespace=~\"open-cluster-management|open-cluster-management-hub\",pod=~\"cluster-manager-.*|managedcluster-import-controller-.*|\",phase!~\"Running|Succeeded\"})[12h:12h])"
    },
    {
     "expr": "sum_over_time(sum by (cluster) (kube_pod_status_phase{namespace=~\"open-cluster-management|open-cluster-management-hub\",pod=~\"cluster-manager-.*|managedcluster-import-controller-.*|\",phase!~\"Running|Succeeded\"})[6h:6h])"
    },
    {
     "expr": "sum_over_time(sum by (cluster) (kube_pod_status_phase{namespace=~\"open-cluster-management|open-cluster-management-hub\",pod=~\"cluster-manager-.*|managedcluster-import-controller-.*|\",phase!~\"Running|Succeeded\"})[1h:1h])"
    }
   ]
  },
  {
   "title": "Pod Restarts Increase",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (increase(kube_pod_container_status_restarts_total{namespace=~\"open-cluster-management|open-cluster-management-hub\",pod=~\"cluster-manager-.*|managedcluster-import-controller-.*|\"}[$__rate_interval])) by (cluster)"
    }
   ]
  },
  {
   "title": "Up",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "sum(up{namespace=~\"open-cluster-management|open-cluster-management-hub\",pod=~\"cluster-manager-.*|managedcluster-import-controller-.*|\"} == 1) by (cluster) / count(up{namespace=~\"open-cluster-management|open-cluster-management-hub\",pod=~\"cluster-manager-.*|managedcluster-import-controller-.*|\"}) by (cluster)"
    }
   ]
  },
  {
   "title": "Managed Clusters Status",
   "type": "table",
   "description": "Shows the status of managed clusters.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum by (cluster) (open_cluster_management_managed_cluster_ready_clusters_number)"
    },
    {
     "expr": "sum by (cluster) (open_cluster_management_managed_cluster_unknown_clusters_number)"
    },
    {
     "expr": "sum by (cluster) (open_cluster_management_managed_cluster_degraded_clusters_number)"
    }
   ]
  },
  {
   "title": "Managed Cluster Addons Status",
   "type": "table",
   "description": "Shows the status of managed clusters.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "sum by (cluster) (open_cluster_management_managed_cluster_ready_addons_number)"
    },
    {
     "expr": "sum by (cluster) (open_cluster_management_managed_cluster_unknown_addons_number)"
    },
    {
     "expr": "sum by (cluster) (open_cluster_management_managed_cluster_degraded_addons_number)"
    }
   ]
  },
  {
   "title": "Cluster Create Rate",
   "type": "graph",
   "description": "Shows rate of cluster import for the given time.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (cluster) (rate(open_cluster_management_managed_cluster_created_total[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Cluster Create Errors",
   "type": "graph",
   "description": "Shows ratio of errors compared to the the total number of cluster import.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (cluster) (rate(open_cluster_management_managed_cluster_create_failure_total{}[$__rate_interval])) / sum by (cluster) (rate(open_cluster_management_managed_cluster_created_total{}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Cluster Create Latency 99th Percentile",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "m" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (cluster, le) (open_cluster_management_managed_cluster_create_durating_seconds{}))"
    }
   ]
  },
  {
   "title": "Cluster Import Rate",
   "type": "graph",
   "description": "Shows rate of cluster import for the given time.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (cluster) (rate(open_cluster_management_managed_cluster_imported_total[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Cluster Import Errors",
   "type": "graph",
   "description": "Shows ratio of errors compared to the the total number of cluster import.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 20 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (cluster) (rate(open_cluster_management_managed_cluster_import_failure_total{}[$__rate_interval])) / sum by (cluster) (rate(open_cluster_management_managed_cluster_imported_total{}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Cluster Import Latency 99th Percentile",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 20 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (cluster, le) (open_cluster_management_managed_cluster_import_durating_seconds{}))"
    }
   ]
  },
  {
   "title": "Governance Policy",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pod Error Count",
     "type": "table",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "sum_over_time(sum by (cluster) (kube_pod_status_phase{namespace=\"open-cluster-management\",pod=~\"grc-.*|policyreport-.*\",phase!~\"Running|Succeeded\"})[24h:24h])"
      },
      {
       "expr": "sum_over_time(sum by (cluster) (kube_pod_status_phase{namespace=\"open-cluster-management\",pod=~\"grc-.*|policyreport-.*\",phase!~\"Running|Succeeded\"})[12h:12h])"
      },
      {
       "expr": "sum_over_time(sum by (cluster) (kube_pod_status_phase{namespace=\"open-cluster-management\",pod=~\"grc-.*|policyreport-.*\",phase!~\"Running|Succeeded\"})[6h:6h])"
      },
      {
       "expr": "sum_over_time(sum by (cluster) (kube_pod_status_phase{namespace=\"open-cluster-management\",pod=~\"grc-.*|policyreport-.*\",phase!~\"Running|Succeeded\"})[1h:1h])"
      }
     ]
    },
    {
     "title": "Pod Restarts Increase",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum (increase(kube_pod_container_status_restarts_total{namespace=\"open-cluster-management\",pod=~\"grc-.*|policyreport-.*\"}[$__rate_interval])) by (cluster)"
      }
     ]
    },
    {
     "title": "Up",
     "type": "table",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 2 },
     "targets": [
      {
       "expr": "sum(up{namespace=\"open-cluster-management\",pod=~\"grc-.*|policyreport-.*\"} == 1) by (cluster) / count(up{namespace=\"open-cluster-management\",pod=~\"grc-.*|policyreport-.*\"}) by (cluster)"
      }
     ]
    },
    {
     "title": "Reconcile Rate",
     "type": "graph",
     "description": "How fast new requests to be reconciled by controller.",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(grc_policy_reconcile_total{job=\"governance-policy-propagator\"}[$__rate_interval])) by (cluster)"
      }
     ]
    },
    {
     "title": "Reconcile Error Ratio",
     "type": "graph",
     "description": "Shows ratio of errors compared to the the total number of reconciles.",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 8 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum by (cluster) (rate(grc_policy_reconcile_failure_total[$__rate_interval])) / sum by (cluster) (rate(grc_policy_reconcile_total[$__rate_interval]))"
      }
     ]
    },
    {
     "title": "Reconcile Duration 99th Percentile",
     "type": "graph",
     "description": "Shows how long has it taken to reconcile reconcile 99% percent requests.",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 8 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by (cluster, le) (grc_policy_reconcile_duration_seconds{}))"
      }
     ]
    },
    {
     "title": "Workqueue Depth",
     "type": "graph",
     "description": "Number of actions waiting in the queue to be performed.",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(workqueue_depth{job=\"governance-policy-propagator\"}[$__rate_interval])) by (cluster)"
      }
     ]
    },
    {
     "title": "Workqueue Add Rate",
     "type": "graph",
     "description": "How fast we are scheduling new actions to be performed by controller.",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(workqueue_adds_total{job=\"governance-policy-propagator\"}[$__rate_interval])) by (cluster)"
      }
     ]
    },
    {
     "title": "Policy Apply Rate",
     "type": "graph",
     "description": "Shows rate of applied polices for the given time.",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (cluster) (rate(policy_applied_total[$__rate_interval]))"
      }
     ]
    },
    {
     "title": "Policy Report Ratio",
     "type": "graph",
     "description": "Shows ratio of reported policies compared to the the total number of propagated policies.",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 20 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum by (cluster) (rate(policy_status_report_total[$__rate_interval])) / sum by (cluster) (rate(policy_propagated_total{}[$__rate_interval]))"
      }
     ]
    },
    {
     "title": "Policy Status Report Latency 99th Percentile",
     "type": "graph",
     "description": "Shows how long has it taken from policy created to status reported.",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 20 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by (cluster, le) (policy_status_report_duration_seconds{}))"
      }
     ]
    }
   ]
  },
  {
   "title": "Application Lifecycle",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pod Error Count",
     "type": "table",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 27 },
     "targets": [
      {
       "expr": "sum_over_time(sum by (cluster) (kube_pod_status_phase{namespace=\"open-cluster-management\",pod=~\"application-.*\",phase!~\"Running|Succeeded\"})[24h:24h])"
      },
      {
       "expr": "sum_over_time(sum by (cluster) (kube_pod_status_phase{namespace=\"open-cluster-management\",pod=~\"application-.*\",phase!~\"Running|Succeeded\"})[12h:12h])"
      },
      {
       "expr": "sum_over_time(sum by (cluster) (kube_pod_status_phase{namespace=\"open-cluster-management\",pod=~\"application-.*\",phase!~\"Running|Succeeded\"})[6h:6h])"
      },
      {
       "expr": "sum_over_time(sum by (cluster) (kube_pod_status_phase{namespace=\"open-cluster-management\",pod=~\"application-.*\",phase!~\"Running|Succeeded\"})[1h:1h])"
      }
     ]
    },
    {
     "title": "Pod Restarts Increase",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum (increase(kube_pod_container_status_restarts_total{namespace=\"open-cluster-management\",pod=~\"application-.*\"}[$__rate_interval])) by (cluster)"
      }
     ]
    },
    {
     "title": "Up",
     "type": "table",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 27 },
     "targets": [
      {
       "expr": "sum(up{namespace=\"open-cluster-management\",pod=~\"application-.*\"} == 1) by (cluster) / count(up{namespace=\"open-cluster-management\",pod=~\"application-.*\"}) by (cluster)"
      }
     ]
    },
    {
     "title": "Reconcile Rate",
     "type": "graph",
     "description": "How fast new requests to be reconciled by controller.",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(application_reconcile_total{job=\"application\"}[$__rate_interval])) by (cluster)"
      }
     ]
    },
    {
     "title": "Reconcile Error Ratio",
     "type": "graph",
     "description": "Shows ratio of errors compared to the the total number of reconciles.",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 33 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum by (cluster) (rate(application_reconcile_failure_total[$__rate_interval])) / sum by (cluster) (rate(application_reconcile_total[$__rate_interval]))"
      }
     ]
    },
    {
     "title": "Reconcile Duration 99th Percentile",
     "type": "graph",
     "description": "Shows how long has it taken to reconcile the 99% requests.",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 33 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by (cluster, le) (application_reconcile_duration_seconds{}))"
      }
     ]
    },
    {
     "title": "Workqueue Depth",
     "type": "graph",
     "description": "Number of actions waiting in the queue to be performed.",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 39 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(workqueue_depth{job=\"application\"}[$__rate_interval])) by (cluster)"
      }
     ]
    },
    {
     "title": "Workqueue Add Rate",
     "type": "graph",
     "description": "How fast we are scheduling new actions to be performed by controller.",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 39 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(workqueue_adds_total{job=\"application\"}[$__rate_interval])) by (cluster)"
      }
     ]
    },
    {
     "title": "Application Apply Rate",
     "type": "graph",
     "description": "Shows rate of created applications for the given time.",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 45 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (cluster) (rate(application_applied_total{}[$__rate_interval]))"
      }
     ]
    },
    {
     "title": "Application Error Ratio",
     "type": "graph",
     "description": "Shows ratio of errored applications compared to the the total number of applications.",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 45 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum by (cluster) (rate(application_apply_failure_total[$__rate_interval])) / sum by (cluster) (rate(application_applied_total[$__rate_interval]))"
      }
     ]
    },
    {
     "title": "Application Apply Latency 99th Percentile",
     "type": "graph",
     "description": "Shows how long has it taken to apply the applications to managed clusters.",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 45 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by (cluster, le) (applicartion_apply_duration_seconds{}))"
      }
     ]
    }
   ]
  },
  {
   "title": "Observability",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pod Error Count",
     "type": "table",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 52 },
     "targets": [
      {
       "expr": "sum_over_time(sum by (cluster) (kube_pod_status_phase{namespace=\"open-cluster-management-observability\",phase!~\"Running|Succeeded\"})[24h:24h])"
      },
      {
       "expr": "sum_over_time(sum by (cluster) (kube_pod_status_phase{namespace=\"open-cluster-management-observability\",phase!~\"Running|Succeeded\"})[12h:12h])"
      },
      {
       "expr": "sum_over_time(sum by (cluster) (kube_pod_status_phase{namespace=\"open-cluster-management-observability\",phase!~\"Running|Succeeded\"})[6h:6h])"
      },
      {
       "expr": "sum_over_time(sum by (cluster) (kube_pod_status_phase{namespace=\"open-cluster-management-observability\",phase!~\"Running|Succeeded\"})[1h:1h])"
      }
     ]
    },
    {
     "title": "Pod Restarts Increase",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 52 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum (increase(kube_pod_container_status_restarts_total{namespace=\"open-cluster-management-observability\"}[$__rate_interval])) by (cluster)"
      }
     ]
    },
    {
     "title": "Up",
     "type": "table",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 52 },
     "targets": [
      {
       "expr": "sum(up{namespace=\"open-cluster-management-observability\"} == 1) by (cluster) / count(up{namespace=\"open-cluster-management-observability\"}) by (cluster)"
      }
     ]
    },
    {
     "title": "Observability Metrics Push Rate",
     "type": "graph",
     "description": "Shows rate of metrics push for the given time.",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 58 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (cluster) (rate(observability_metrics_push_total{}[$__rate_interval]))"
      }
     ]
    },
    {
     "title": "Observability Metrics Push Errors",
     "type": "graph",
     "description": "Shows ratio of errors compared to the the total number of metrics puesh.",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 58 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum by (cluster) (rate(observability_metrics_push_failure_total[$__rate_interval])) / sum by (cluster) (rate(observability_metrics_push_total[$__rate_interval]))"
      }
     ]
    },
    {
     "title": "Observability Metrics Push Latency 99th Percentile",
     "type": "graph",
     "description": "Shows how long has it taken to push metrics.",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 58 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by (cluster, le) (observability_metrics_push_duration_seconds{}))"
      }
     ]
    },
    {
     "title": "Observability Instant Query Rate",
     "type": "graph",
     "description": "Shows rate of metrics push for the given time.",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 64 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (cluster) (rate(observability_instant_query_total{}[$__rate_interval]))"
      }
     ]
    },
    {
     "title": "Observability Instant Query Errors",
     "type": "graph",
     "description": "Shows ratio of errors compared to the the total number of metrics puesh.",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 64 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum by (cluster) (rate(observability_instant_query_failure_total[$__rate_interval])) / sum by (cluster) (rate(observability_instant_query_total[$__rate_interval]))"
      }
     ]
    },
    {
     "title": "Observability Instant Query Latency 99th Percentile",
     "type": "graph",
     "description": "Shows how long has it taken to push metrics.",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 64 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by (cluster, le) (observability_instant_query_duration_seconds{}))"
      }
     ]
    },
    {
     "title": "Observability Range Query Rate",
     "type": "graph",
     "description": "Shows rate of metrics push for the given time.",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 70 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (cluster) (rate(observability_range_query_total{}[$__rate_interval]))"
      }
     ]
    },
    {
     "title": "Observability Range Query Errors",
     "type": "graph",
     "description": "Shows ratio of errors compared to the the total number of metrics puesh.",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 70 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum by (cluster) (rate(observability_range_query_failure_total[$__rate_interval])) / sum by (cluster) (rate(observability_range_query_total[$__rate_interval]))"
      }
     ]
    },
    {
     "title": "Observability Range Query Latency 99th Percentile",
     "type": "graph",
     "description": "Shows how long has it taken to push metrics.",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 70 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by (cluster, le) (observability_range_query_duration_seconds{}))"
      }
     ]
    }
   ]
  }
 ]
}